# -*- coding: utf-8 -*-
"""Cyber_Automation_Playbook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBADvtxH3RV857vwBCiLwMcK4xrGee9N
"""

# Cloud SIEM Threat Detection and Response Using Python and Sumo Logic

## 1. Import Required Libraries

import requests
import json
import time
import random
from datetime import datetime
import folium

## 2. Configure Sumo Logic Webhook

SUMO_WEBHOOK_URL = "https://endpoint4.collection.sumologic.com/receiver/v1/http/ZaVnC4dhaV27ZKY4ncGiGGRu85Vj9qK-cmNBdrUx2LCDmsNdt42XcklFxYTH1HFRyyUjRhNr15cb2rv-0NEydYPAlrN2wffVT7WF2_1ZxWJbmm4OU-vv6Q=="
## 3. Threat Intelligence Feed Integration

# Fetch real-world malicious IP feed
feed_url = "https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt"

response = requests.get(feed_url)

malicious_ips = []

if response.status_code == 200:

    lines = response.text.split("\n")

    for line in lines:

        # Ignore comments
        if line.startswith("#") or line.strip() == "":
            continue

        ip = line.split()[0]
        malicious_ips.append(ip)

     # Randomly select up to 100 IPs from the threat feed
    malicious_ips = random.sample(
    malicious_ips,
    min(100, len(malicious_ips)))

    print("[SUCCESS] Random Threat Feed Loaded")
    print("Loaded malicious IPs:", len(malicious_ips))
    print("Sample IPs:", malicious_ips[:5])

   # Shows first 5 selected IPs

else:
    print("[ERROR] Failed to fetch threat feed.")

### GeoIP Enrichment

def geoip_lookup(ip):

    try:
        url = f"https://ipwho.is/{ip}"

        response = requests.get(url)

        data = response.json()

        if data.get("success"):
          return {
        "country": data.get("country", "Unknown"),
        "city": data.get("city", "Unknown"),
        "continent": data.get("continent", "Unknown"),
        "isp": data.get("connection", {}).get("isp", "Unknown"),
        "organization": data.get("connection", {}).get("org", "Unknown"),
        "asn": data.get("connection", {}).get("asn", "Unknown"),
        "latitude": data.get("latitude"),
        "longitude": data.get("longitude")
    }

    except Exception as e:
      print(f"GeoIP Lookup Error: {e}")

    return {
    "country": "Unknown",
    "city": "Unknown",
    "continent": "Unknown",
    "isp": "Unknown",
    "organization": "Unknown",
    "asn": "Unknown",
    "latitude": None,
    "longitude": None
}

## 4.Dynamic Cyber Attack Logs

event_types = [
    "brute_force",
    "sql_injection",
    "directory_traversal",
    "credential_dumping",
    "command_execution",
    "data_exfiltration",
    "phishing",
    "port_scanning"
]

endpoints = [
    "/api/v1/auth/login",
    "/login?id=1 OR 1=1",
    "/../../etc/passwd",
    "/cmd.exe",
    "/export-data",
    "/fake-login-page",
    "/multiple-ports"
]

attack_logs = []

for ip in malicious_ips[:20]:

        attack_logs.append({

        "src_ip": ip,

        "event_type": random.choice(event_types),

        "method": random.choice(["GET", "POST"]),

        "endpoint": random.choice(endpoints),

        "status_code": random.choice([200, 401, 403, 404, 500]),

        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    })

# Add one trusted internal system

attack_logs.append({

    "src_ip": "192.168.1.50",

    "event_type": "normal_activity",

    "method": "GET",

    "endpoint": "/dashboard",

    "status_code": 200,

    "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")

})



## 5. SOC Detection Engineering Logic

# Threshold tracking
failed_login_count = {}

# Correlation tracking
endpoint_tracker = {}

# MITRE ATT&CK mapping
mitre_mapping = {

    "brute_force": "T1110",

    "sql_injection": "T1190",

    "directory_traversal": "T1083",

    "recon_scan": "T1595",

    "phishing": "T1566",

    "credential_dumping": "T1003",

    "command_execution": "T1059",

    "data_exfiltration": "T1041",

    "port_scanning": "T1046",

    "normal_activity": "None"
}


# Whitelist logic
whitelist_ips = ["192.168.1.50"]

# -------------------------
# Email Alert Simulation
# -------------------------

def send_email_alert(log):

    print("\n========================================")
    print("🚨 SOC EMAIL ALERT")
    print("========================================")
    print("Subject : CRITICAL SECURITY ALERT")
    print(f"Source IP      : {log['src_ip']}")
    print(f"Country        : {log['country']}")
    print(f"City           : {log['city']}")
    print(f"Attack Type    : {log['event_type']}")
    print(f"MITRE ATT&CK   : {log['mitre_technique']}")
    print(f"Severity       : {log['severity']}")
    print(f"Risk Score     : {log['risk_score']}")
    print(f"Firewall Action: {log['firewall_action']}")
    print("========================================\n")

# -------------------------
# Incident Report Generation
# -------------------------

def generate_incident_report(log):

    print("\n========================================")
    print("📄 INCIDENT REPORT")
    print("========================================")
    print(f"Source IP        : {log['src_ip']}")
    print(f"Country          : {log['country']}")
    print(f"City             : {log['city']}")
    print(f"Attack Type      : {log['event_type']}")
    print(f"MITRE Technique  : {log['mitre_technique']}")
    print(f"Severity         : {log['severity']}")
    print(f"Risk Score       : {log['risk_score']}")
    print(f"Firewall Action  : {log['firewall_action']}")
    print("Status           : Incident Logged")
    print("========================================\n")

    filename = "Incident_Reports.txt"

    with open(filename, "a") as file:

      file.write("\n========================================\n")
      file.write("INCIDENT REPORT\n")
      file.write("========================================\n")
      file.write(f"Timestamp         : {log['timestamp']}\n")
      file.write(f"Source IP         : {log['src_ip']}\n")
      file.write(f"Country           : {log['country']}\n")
      file.write(f"City              : {log['city']}\n")
      file.write(f"Attack Type       : {log['event_type']}\n")
      file.write(f"MITRE Technique   : {log['mitre_technique']}\n")
      file.write(f"Severity          : {log['severity']}\n")
      file.write(f"Risk Score        : {log['risk_score']}\n")
      file.write(f"Firewall Action   : {log['firewall_action']}\n")
      file.write("========================================\n\n")

# -------------------------
# Trend Analysis
# -------------------------

def generate_trend_analysis(logs):

    attack_count = {}
    severity_count = {}
    country_count = {}

    for log in logs:

        attack = log["event_type"]
        attack_count[attack] = attack_count.get(attack, 0) + 1

        severity = log["severity"]
        severity_count[severity] = severity_count.get(severity, 0) + 1

        country = log["country"]
        country_count[country] = country_count.get(country, 0) + 1

    print("\n========================================")
    print("📊 SOC TREND ANALYSIS")
    print("========================================")

    print("\nAttack Types")
    for attack, count in attack_count.items():
        print(f"{attack:<25} {count}")

    print("\nSeverity Distribution")
    for severity, count in severity_count.items():
        print(f"{severity:<25} {count}")

    print("\nTop Source Countries")
    for country, count in sorted(country_count.items(),
                                 key=lambda x: x[1],
                                 reverse=True):
        print(f"{country:<25} {count}")

    print("========================================\n")

# -------------------------
# World Attack Map
# -------------------------

def generate_attack_map(logs):

    attack_map = folium.Map(location=[20, 0], zoom_start=2)

    for log in logs:

        try:

            if log["latitude"] is not None and log["longitude"] is not None:

                folium.Marker(
                    location=[log["latitude"], log["longitude"]],
                    popup=(
                        f"IP: {log['src_ip']}<br>"
                        f"Country: {log['country']}<br>"
                        f"Attack: {log['event_type']}<br>"
                        f"Risk Score: {log['risk_score']}"
                    ),
                    tooltip=log["country"]
                ).add_to(attack_map)

        except Exception:
            pass

    attack_map.save("SOC_Attack_Map.html")

    print("\n🌍 Attack Map saved as: SOC_Attack_Map.html")

# -------------------------
# Executive SOC Report
# -------------------------

def generate_executive_report(logs):

    total_logs = len(logs)

    critical = sum(1 for log in logs if log["severity"] == "critical")

    blocked = sum(1 for log in logs if log["firewall_action"] == "Blocked")

    countries = len(set(log["country"] for log in logs))

    report = f"""
========================================
        EXECUTIVE SOC REPORT
========================================

Total Security Events : {total_logs}

Critical Threats      : {critical}

Blocked Attacks       : {blocked}

Countries Involved    : {countries}

Threat Intelligence   : Enabled

GeoIP Enrichment      : Enabled

MITRE ATT&CK Mapping  : Enabled

Risk Scoring          : Enabled

Email Alerting        : Enabled

Incident Reporting    : Enabled

Automatic Blocking    : Enabled

Overall SOC Status    : OPERATIONAL

========================================
"""

    print(report)

    with open("Executive_SOC_Report.txt", "w") as file:
        file.write(report)

    print("📄 Executive report saved as Executive_SOC_Report.txt")

def soc_dashboard():

    total_events = len(attack_logs)

    critical = sum(
        1 for log in attack_logs
        if log["severity"] == "critical"
    )

    blocked = sum(
        1 for log in attack_logs
        if log["firewall_action"] == "Blocked"
    )

    unique_countries = len(
        set(log["country"] for log in attack_logs)
    )

    print("\n========================================")
    print("        LIVE SOC DASHBOARD")
    print("========================================")
    print(f"Total Events        : {total_events}")
    print(f"Critical Threats    : {critical}")
    print(f"Blocked Attacks     : {blocked}")
    print(f"Countries Involved  : {unique_countries}")
    print("SOC Status          : ACTIVE")
    print("========================================")


## 6. Stream Logs into Sumo Logic

blocked_ips = []

for log in attack_logs:

    ip = log["src_ip"]

    geo = geoip_lookup(ip)

    log["country"] = geo["country"]
    log["city"] = geo["city"]
    log["continent"] = geo["continent"]
    log["isp"] = geo["isp"]
    log["organization"] = geo["organization"]
    log["asn"] = geo["asn"]
    log["latitude"] = geo["latitude"]
    log["longitude"] = geo["longitude"]



    # Threshold brute-force detection
    if log["status_code"] == 401:

        failed_login_count[ip] = failed_login_count.get(ip, 0) + 1

        if failed_login_count[ip] >= 3:
            log["brute_force_detected"] = True
        else:
            log["brute_force_detected"] = False

    else:
        log["brute_force_detected"] = False

    # Correlation scan detection
    endpoint_tracker.setdefault(ip, set()).add(log["endpoint"])

    if len(endpoint_tracker[ip]) >= 2:
        log["scan_detected"] = True
    else:
        log["scan_detected"] = False

    # MITRE ATT&CK mapping
    log["mitre_technique"] = mitre_mapping.get(
        log["event_type"],
        "Unknown"
    )

    # False positive handling
    if ip in whitelist_ips:
        log["whitelisted"] = True
    else:
        log["whitelisted"] = False

    if log["src_ip"] in malicious_ips:
      log["threat_intel_match"] = True
    else:
      log["threat_intel_match"] = False



## 7. Cloud SIEM Log Transmission

# -------------------------
# Risk Score Calculation
# -------------------------
    risk_score = 0

    if log["threat_intel_match"]:
      risk_score += 40

    if log["event_type"] in [
     "credential_dumping",
      "command_execution",
      "data_exfiltration"
  ]:
      risk_score += 30

    if log["brute_force_detected"]:
      risk_score += 10

    if log["scan_detected"]:
     risk_score += 10

    if log["status_code"] == 500:
      risk_score += 10

    log["risk_score"] = min(risk_score, 100)

# -------------------------
# Dynamic Severity
# -------------------------

    if log["risk_score"] >= 70:
      log["severity"] = "critical"

    elif log["risk_score"] >= 50:
      log["severity"] = "high"

    elif log["risk_score"] >= 30:
      log["severity"] = "medium"

    else:
      log["severity"] = "low"

# -------------------------
# Automatic IP Blocking Simulation
# -------------------------

    if log["risk_score"] >= 70 and ip not in blocked_ips:

      blocked_ips.append(ip)


      log["firewall_action"] = "Blocked"
      send_email_alert(log)
      generate_incident_report(log)

      print("\n==============================")
      print("[SOC RESPONSE]")
      print("High-Risk Threat Detected")
      print("IP:", ip)
      print("Risk Score:", log["risk_score"])
      print("Firewall Action: BLOCKED")
      print("==============================\n")

    else:

      log["firewall_action"] = "Allowed"





    response = requests.post(
        SUMO_WEBHOOK_URL,
        data=json.dumps(log),
        headers={"Content-Type": "application/json"}
    )

    print(response.status_code)


    print(json.dumps(log, indent=4))
    time.sleep(1)

print("[SUCCESS] Security logs transmitted to Sumo Logic Cloud SIEM.")

generate_trend_analysis(attack_logs)
generate_attack_map(attack_logs)
generate_executive_report(attack_logs)


print("\n========================================")
print("      MITRE ATT&CK SUMMARY")
print("========================================")

mitre_count = {}

for log in attack_logs:
      technique = log["mitre_technique"]
      mitre_count[technique] = mitre_count.get(technique, 0) + 1

for technique, count in sorted(
        mitre_count.items(),
        key=lambda x: x[1],
        reverse=True):

    print(f"{technique:15} {count}")

print("========================================")

soc_dashboard()

print("\n========================================")
print("        IOC SUMMARY")
print("========================================")

print("Malicious Source IPs")

for log in attack_logs:

    if log["threat_intel_match"]:

        print(
            f"{log['src_ip']:18}"
            f"{log['country']:15}"
            f"{log['event_type']}"
        )

print("========================================")

!pip install folium

import os
os.listdir()
